### ISSUE TITLE
4 subprocess-spawning test files time out under full-suite parallel load — they pass in isolation, and clean-install runs the parallel form

### ISSUE THREAD

**Issue by jjackson** [jjackson/ace#1912]
## Symptom

`npm test` (= `npx vitest run`, the full parallel suite) fails 5 tests across 4 files. Every one of them passes when the file is run on its own.

```
$ npm test
 Test Files  3 failed | 404 passed | 7 skipped (414)
      Tests  5 failed | 6198 passed | 33 skipped (6236)

 ❯ test/mcp/mobile/session-lock-e2e.test.ts (5 tests | 3 failed) 20951ms
     × two concurrent subprocesses both acquire distinct locks              5017ms
     × reaper sweeps the SIGKILLed lock; live sibling lock is preserved     5003ms
     × reaper with --all removes EVERY lock including the alive sibling     5006ms
 ❯ test/lib/version-bump.test.ts (11 tests | 1 failed) 22209ms
     × --rebase-first auto-resolves a package-lock.json conflict (ace#1778) 5573ms
 ❯ test/scripts/run-xform-patch.test.ts (6 tests | 1 failed) 20394ms
     × honors --replace-existing by stripping prior <image> values          6641ms
 ❯ test/scripts/doctor-env-freshness.test.ts (10 tests | 1 failed) 30759ms
     × exits 0 on every path so bin/ace-doctor is never broken by its probe 5041ms
```

Isolated, all four files are green:

```
$ npx vitest run test/scripts/doctor-env-freshness.test.ts
 Test Files  1 passed (1)      Tests  10 passed (10)     Duration 11.30s

$ npx vitest run test/mcp/mobile/session-lock-e2e.test.ts test/lib/version-bump.test.ts test/scripts/run-xform-patch.test.ts
 Test Files  3 passed (3)      Tests  22 passed (22)     Duration 11.74s
```

## Root cause (hypothesis, not yet confirmed)

All four files spawn real subprocesses (`spawnLockHolder`, `version-bump.sh`, `run-xform-patch.ts`, the doctor probe). Every failure lands at **~5.0s**, which reads as a fixed per-assertion timeout being exceeded because the box is saturated by 414 parallel test files — not as a logic defect. The suite's own `import` phase reports 101s against 42s wall-clock, i.e. heavy oversubscription.

Not yet verified: which timeout is the binding one (vitest `testTimeout` vs. a helper's internal wait), and whether pinning `poolOptions.threads.maxThreads` or marking these four files `sequential` clears it.

## Why it matters (blast radius)

`.github/workflows/clean-install.yml:67` runs `npx vitest run` — the parallel form. `clean-install` is `main`'s **only required check**, so this flake class can redden a PR that changed nothing related, and (worse) trains readers to re-run CI on red rather than read it. It also makes `npm test` unusable as a local pre-PR gate, which is where the self-heal sweep's negative controls are supposed to be proven.

## Fix lands here

`vitest.config.ts` (pool/concurrency or a per-file `sequential` marker), or per-file timeouts in the four named tests.

## Repro

`npm test` on a clean checkout of `main` @ `d2345ab1`, macOS 25.6.0, node from repo `package.json`. Observed 2026-09-02.

**Comment by jjackson** [comment]
**Correction to the blast-radius claim — CI has NOT been observed failing on this.**

The issue body says the flake "can redden a PR that changed nothing related". That is a *prediction*, and I should not have stated it without a CI observation behind it. The first PR shipped after filing (#1913) ran `clean-install` green in **1m22s**:

```
clean-install   pass   1m22s
check-version   pass   8s
```

So the evidence so far is **local-only**: 5 failures across 4 files on macOS under `npm test`, all green in isolation. GitHub's runner may simply not oversubscribe the way this workstation does — 414 test files against however many local cores, versus a dedicated `ubuntu-latest` box.

What survives unchanged:

- The four files DO fail locally under the parallel form and pass in isolation. That is reproducible and still worth fixing, because it makes `npm test` unusable as a local pre-PR gate — which is where negative controls get proven.
- The ~5.0s clustering still points at a timeout under load rather than a logic defect.

What needs an actual observation before anyone acts on it:

- whether `clean-install` has ever gone red on these four files. `gh run list --workflow clean-install.yml --status failure` over a window would settle it. If it never has, this is a **local dev-experience** issue, not a CI-reliability one, and should be re-labelled and de-prioritised accordingly.

Flagging it myself rather than leaving a plausible-sounding premise in the tracker — per `CLAUDE.md` § "Verify the premise against the artifact, and quote what you ran."

**Comment by jjackson** [comment]
**Settled — and the answer refutes my own hypothesis. `clean-install` is not flaking on these files at all.**

I said above that this needed an actual observation before anyone acted on it. Ran it. Over the last **60 `clean-install` runs**, 14 failed (23%), and I classified every one by reading its failed-job log:

| Cause | Count |
|---|---|
| **VERSION-collision guard** (`check-version-unique`) | **12** |
| type-check (`error TS1117`, duplicate object keys) | 1 |
| other | 1 |
| **the four subprocess test files** | **0** |

```
$ gh run list --workflow clean-install.yml --limit 60 --json conclusion,databaseId \
    --jq '.[]|select(.conclusion=="failure")|.databaseId' | while read id; do ... done | sort | uniq -c
  12 VERSION-collision guard
   1 type-check
   1 other
```

In the failures I opened, the vitest step was **green** — e.g. run `33555615140`:

```
Tests  5971 passed | 79 skipped (6050)
##[error]main was pushed WITHOUT advancing VERSION.
```

So the blast-radius claim in the issue body is **wrong**, not merely unproven. `ubuntu-latest` evidently does not oversubscribe the way this workstation does. **Re-scoping this to a local dev-experience issue**: `npm test` is unreliable as a *local* pre-PR gate on macOS, which still matters (it is where negative controls get proven), but it is not a CI-reliability problem and should not be prioritised as one.

---

**The far more interesting finding, which I was not looking for.** 12 of 14 `clean-install` failures — 20% of *all* runs — are the VERSION-collision guard, and **at least two fired on `main` itself** (`--post-merge`), meaning a change landed on `main` unreachable by `/ace:update` until a follow-up bump. That is `ace#1593`'s failure mode still happening at volume.

This is directly load-bearing for the self-heal work in #1913. That PR records VERSION contention as "a solved, one-rebase-per-collision cost" and rules it out as a reason to stop shipping fixes. The recipe *is* correct and the guard *is* doing its job — but at a 20% strike rate it is plainly not cheap enough in practice for anyone to experience it as solved, which is exactly why the `bednet-o0sen` sweep cited "five PRs raced for VERSION" as a reason to stop at 5. The guard converts a silent corruption into a loud failure, which is right; it does not reduce the contention.

Worth its own issue (serialize the bump, or claim the version at PR-open rather than at commit) — filing separately rather than growing this one, since it is a different defect with a different fix site.

**Comment by jjackson** [comment]
**Fixed and merged in #1941 (v0.13.1156).** Your hypothesis was right, including the part you flagged as unverified.

## Your own two corrections stand

I re-checked the CI half before doing anything and did not re-litigate it: your 60-run classification (12 VERSION-collision, 1 type-check, 1 other, **0** these files) is the evidence, and this shipped as a **local dev-experience** fix, not a CI-reliability one. Nothing in #1941 claims otherwise.

## Reproducing it — a single suite is not enough, which is why the premise looked shaky

On an 18-core box, `npx vitest run` alone **never** reproduced it: **0 of 16** consecutive runs. Induced CPU load didn't do it either (36 burners; transform 13s→22s, setup 5s→10s, so the load was real — still 0 of 4).

What reproduces it reliably is **two full suites concurrently**, which contends on subprocess *spawning* rather than just CPU. On `main` @ `7336f2f0`, 6 runs:

```
   5  test/mcp/mobile/session-lock-e2e.test.ts    5003, 5005, 5235, 5371, 5649 ms
   4  test/lib/version-bump.test.ts               5078, 5104, 5557, 5699 ms
   1  test/scripts/run-xform-patch.test.ts        5160 ms
```

Every one of the 10:

```
Error: Test timed out in 5000ms.
If this is a long-running test, pass a timeout value as the last argument
or configure it globally with "testTimeout".
```

That answers the question your "Root cause (hypothesis, not yet confirmed)" section left open — **the binding timeout is vitest's `testTimeout`, not any helper's internal wait.** And your read of the ~5.0s clustering was exactly right: they all land *just over* the line, never far past it.

## One thing the issue understated

The four files are not special:

```
$ grep -rl "node:child_process" test/ | wc -l
20
$ for f in $(grep -rl "node:child_process" test/); do grep -c "testTimeout" $f; done | sort -u
0
```

**20 files spawn real subprocesses and none declared a timeout.** The four you saw are the ones that fired that day. So the fix went to the class rather than the instances: `testTimeout` + `hookTimeout` at 30s in `vitest.config.ts` (`hookTimeout` independently — beforeEach/afterEach in these files spawn too, and its default is 10000ms).

I did **not** take the `sequential` route the issue suggested: the contention is box-wide, not intra-file, so marking files sequential does not address it.

A second bound surfaced only after the first was raised — `session-lock-e2e.test.ts:346`'s own hardcoded 10s wait for a spawned daemon (`daemon never reported LISTENING` at 10026ms), now 60s to match `spawnLockHolder`'s existing bound. Found by re-running the control, not predicted.

## Controls

| | result |
|---|---|
| pre-fix, 6 concurrent runs | 10 × `Test timed out in 5000ms` across 3 files |
| post-fix, 8 concurrent runs | **0** occurrences; `version-bump` and `run-xform-patch` clean |
| post-fix, single suite (the CI form) | 5 of 5 green |

Guard: `test/subprocess-test-timeout.test.ts` re-derives the subprocess-spawning file list rather than hardcoding it, so a new one is covered the moment it lands, and asserts the list is non-empty so it fails loudly instead of going inert.

## Residual, named rather than fixed

Under **two concurrent full suites**, `session-lock-e2e`'s *"SIGTERM-driven cleanup kills daemons on lock ports before releasing the lock"* still fails ~**1 in 8** with `Error: Test timed out in 30000ms`. That is a **6× overshoot, not a near miss**, so it is a genuinely slow daemon-shutdown path under contention and raising the ceiling again would paper over it. Redesigning that shutdown/port-release protocol was out of scope. It does not appear in the single-suite form (0 of 5 here, 0 of 12 in #1939's runs). **Falsified by:** the same test timing out under a single suite, or on CI.

## Two adjacent findings from the same investigation

- **#1883 + #1797** — fixed together in **#1939**. They were one defect: `~/.ace/mobile-backend.<ppid>` was a single real file shared by every vitest worker. That was the class *your* four files sat next to, and it accounted for the `client.test.ts` noise in these stress runs.
- **#1942** (new, fixed in #1943) — `client.test.ts`'s `registerTestUser: tempdir lifecycle` tests diff the **global** `os.tmpdir()` for `ace-mobile-reg-*`, so any concurrent registration reds them. Fails fast (462-670ms), not a timeout, so it was never part of this issue — but it is the third member of the same shared-mutable-state family.
